### PR TITLE
Updating to version 2.1.2

### PR DESCRIPTION
**Pull request by tiagofrepereira2012**

### CODE REVIEW

**Comment by 183amir** [comment]
@tiagofrepereira2012 you need to set the build number to `0` on line 2: `{% set build_number = "2" %}`
This feedstock is a little different.

**Comment by tiagofrepereira2012** [comment]
Ok, but this should be automatic, don't you think?

**Comment by 183amir** [comment]
Yes but I haven't had the time to do it yet. It needs an extra regular expression replace.
`{% set build_number = "2" %} --> {% set build_number = "0" %}`
like here: https://gitlab.idiap.ch/bob/bob.extension/blob/master/bob/extension/scripts/new_version.py#L285

**Comment by tiagofrepereira2012** [comment]
Well, I can do it when have the time.
I will edit manually this one.

Thanks

**Comment by 183amir** [comment]
Thank you. I will merge this and keep restarting the CI after merge.

**Comment by 183amir** [comment]
The CI went through without needing a restart this time :smile:

**Pull request merged**
